### ISSUE TITLE
Evaluation sets for G and I criterion

### ISSUE THREAD

**Issue by joncheryl** [mdlerch/OptimalDesign#26]
I'm not sure about the utility of having different candidate and evaluation sets. While using the G-crit could be sped up using a smaller evaluation set, if you're trying to minimize the maximum prediction variance then I think you want your evaluation set to be large. The I-crit isn't going to be sped up any.

I don't think there's any benefit in having the evaluation set be a superset of the candidate set.

**Comment by mdlerch** [comment]
I don't see the evaluation set as a means for making things faster.  I can envision scenarios where you can dial in your treatments for an experiment to, say, the nearest quarter from 0 to 1, however, you are interested in performance across a much finer grid, and thus would like a larger evaluation set than candidate set.

This can be low on the priority list, and I can take care of it since it won't be much of a mental exercise.
